//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("db_lgameModel", "themes_english_letters_tid_fk", "themes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LG.pgDB_manipulator.theme), "themes_english_letters", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LG.pgDB_manipulator.themes_english_letters), true)]
[assembly: EdmRelationshipAttribute("db_lgameModel", "themes_english_pictures_tid_fk", "themes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LG.pgDB_manipulator.theme), "themes_english_pictures", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LG.pgDB_manipulator.themes_english_pictures), true)]
[assembly: EdmRelationshipAttribute("db_lgameModel", "words_tid_fk", "themes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(LG.pgDB_manipulator.theme), "words", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LG.pgDB_manipulator.word), true)]

#endregion

namespace LG.pgDB_manipulator
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities()
            : base("name=db_lgameEntities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<theme> themes
        {
            get
            {
                if ((_themes == null))
                {
                    _themes = base.CreateObjectSet<theme>("themes");
                }
                return _themes;
            }
        }
        private ObjectSet<theme> _themes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<themes_english_letters> themes_english_letters
        {
            get
            {
                if ((_themes_english_letters == null))
                {
                    _themes_english_letters = base.CreateObjectSet<themes_english_letters>("themes_english_letters");
                }
                return _themes_english_letters;
            }
        }
        private ObjectSet<themes_english_letters> _themes_english_letters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<themes_english_pictures> themes_english_pictures
        {
            get
            {
                if ((_themes_english_pictures == null))
                {
                    _themes_english_pictures = base.CreateObjectSet<themes_english_pictures>("themes_english_pictures");
                }
                return _themes_english_pictures;
            }
        }
        private ObjectSet<themes_english_pictures> _themes_english_pictures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<word> words
        {
            get
            {
                if ((_words == null))
                {
                    _words = base.CreateObjectSet<word>("words");
                }
                return _words;
            }
        }
        private ObjectSet<word> _words;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<words_english> words_english
        {
            get
            {
                if ((_words_english == null))
                {
                    _words_english = base.CreateObjectSet<words_english>("words_english");
                }
                return _words_english;
            }
        }
        private ObjectSet<words_english> _words_english;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the themes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTothemes(theme theme)
        {
            base.AddObject("themes", theme);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the themes_english_letters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTothemes_english_letters(themes_english_letters themes_english_letters)
        {
            base.AddObject("themes_english_letters", themes_english_letters);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the themes_english_pictures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTothemes_english_pictures(themes_english_pictures themes_english_pictures)
        {
            base.AddObject("themes_english_pictures", themes_english_pictures);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the words EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTowords(word word)
        {
            base.AddObject("words", word);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the words_english EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTowords_english(words_english words_english)
        {
            base.AddObject("words_english", words_english);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_lgameModel", Name="theme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class theme : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new theme object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static theme Createtheme(global::System.Int32 id)
        {
            theme theme = new theme();
            theme.id = id;
            return theme;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private Nullable<global::System.Int32> _Width;
        partial void OnWidthChanging(Nullable<global::System.Int32> value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private Nullable<global::System.Int32> _Height;
        partial void OnHeightChanging(Nullable<global::System.Int32> value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Left
        {
            get
            {
                return _Left;
            }
            set
            {
                OnLeftChanging(value);
                ReportPropertyChanging("Left");
                _Left = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Left");
                OnLeftChanged();
            }
        }
        private Nullable<global::System.Int32> _Left;
        partial void OnLeftChanging(Nullable<global::System.Int32> value);
        partial void OnLeftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Top
        {
            get
            {
                return _Top;
            }
            set
            {
                OnTopChanging(value);
                ReportPropertyChanging("Top");
                _Top = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Top");
                OnTopChanged();
            }
        }
        private Nullable<global::System.Int32> _Top;
        partial void OnTopChanging(Nullable<global::System.Int32> value);
        partial void OnTopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.String _Data;
        partial void OnDataChanging(global::System.String value);
        partial void OnDataChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_lgameModel", "themes_english_letters_tid_fk", "themes_english_letters")]
        public EntityCollection<themes_english_letters> themes_english_letters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<themes_english_letters>("db_lgameModel.themes_english_letters_tid_fk", "themes_english_letters");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<themes_english_letters>("db_lgameModel.themes_english_letters_tid_fk", "themes_english_letters", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_lgameModel", "themes_english_pictures_tid_fk", "themes_english_pictures")]
        public EntityCollection<themes_english_pictures> themes_english_pictures
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<themes_english_pictures>("db_lgameModel.themes_english_pictures_tid_fk", "themes_english_pictures");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<themes_english_pictures>("db_lgameModel.themes_english_pictures_tid_fk", "themes_english_pictures", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_lgameModel", "words_tid_fk", "words")]
        public EntityCollection<word> words
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<word>("db_lgameModel.words_tid_fk", "words");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<word>("db_lgameModel.words_tid_fk", "words", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_lgameModel", Name="themes_english_letters")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class themes_english_letters : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new themes_english_letters object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static themes_english_letters Createthemes_english_letters(global::System.Int32 id)
        {
            themes_english_letters themes_english_letters = new themes_english_letters();
            themes_english_letters.id = id;
            return themes_english_letters;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tid
        {
            get
            {
                return _tid;
            }
            set
            {
                OntidChanging(value);
                ReportPropertyChanging("tid");
                _tid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tid");
                OntidChanged();
            }
        }
        private Nullable<global::System.Int32> _tid;
        partial void OntidChanging(Nullable<global::System.Int32> value);
        partial void OntidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String letter
        {
            get
            {
                return _letter;
            }
            set
            {
                OnletterChanging(value);
                ReportPropertyChanging("letter");
                _letter = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("letter");
                OnletterChanged();
            }
        }
        private global::System.String _letter;
        partial void OnletterChanging(global::System.String value);
        partial void OnletterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> left
        {
            get
            {
                return _left;
            }
            set
            {
                OnleftChanging(value);
                ReportPropertyChanging("left");
                _left = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("left");
                OnleftChanged();
            }
        }
        private Nullable<global::System.Int32> _left;
        partial void OnleftChanging(Nullable<global::System.Int32> value);
        partial void OnleftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> top
        {
            get
            {
                return _top;
            }
            set
            {
                OntopChanging(value);
                ReportPropertyChanging("top");
                _top = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("top");
                OntopChanged();
            }
        }
        private Nullable<global::System.Int32> _top;
        partial void OntopChanging(Nullable<global::System.Int32> value);
        partial void OntopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rotation
        {
            get
            {
                return _rotation;
            }
            set
            {
                OnrotationChanging(value);
                ReportPropertyChanging("rotation");
                _rotation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rotation");
                OnrotationChanged();
            }
        }
        private Nullable<global::System.Int32> _rotation;
        partial void OnrotationChanging(Nullable<global::System.Int32> value);
        partial void OnrotationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_lgameModel", "themes_english_letters_tid_fk", "themes")]
        public theme theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<theme>("db_lgameModel.themes_english_letters_tid_fk", "themes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<theme>("db_lgameModel.themes_english_letters_tid_fk", "themes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<theme> themeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<theme>("db_lgameModel.themes_english_letters_tid_fk", "themes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<theme>("db_lgameModel.themes_english_letters_tid_fk", "themes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_lgameModel", Name="themes_english_pictures")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class themes_english_pictures : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new themes_english_pictures object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static themes_english_pictures Createthemes_english_pictures(global::System.Int32 id)
        {
            themes_english_pictures themes_english_pictures = new themes_english_pictures();
            themes_english_pictures.id = id;
            return themes_english_pictures;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tid
        {
            get
            {
                return _tid;
            }
            set
            {
                OntidChanging(value);
                ReportPropertyChanging("tid");
                _tid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tid");
                OntidChanged();
            }
        }
        private Nullable<global::System.Int32> _tid;
        partial void OntidChanging(Nullable<global::System.Int32> value);
        partial void OntidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> wid
        {
            get
            {
                return _wid;
            }
            set
            {
                OnwidChanging(value);
                ReportPropertyChanging("wid");
                _wid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("wid");
                OnwidChanged();
            }
        }
        private Nullable<global::System.Int32> _wid;
        partial void OnwidChanging(Nullable<global::System.Int32> value);
        partial void OnwidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> left
        {
            get
            {
                return _left;
            }
            set
            {
                OnleftChanging(value);
                ReportPropertyChanging("left");
                _left = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("left");
                OnleftChanged();
            }
        }
        private Nullable<global::System.Int32> _left;
        partial void OnleftChanging(Nullable<global::System.Int32> value);
        partial void OnleftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> top
        {
            get
            {
                return _top;
            }
            set
            {
                OntopChanging(value);
                ReportPropertyChanging("top");
                _top = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("top");
                OntopChanged();
            }
        }
        private Nullable<global::System.Int32> _top;
        partial void OntopChanging(Nullable<global::System.Int32> value);
        partial void OntopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rotation
        {
            get
            {
                return _rotation;
            }
            set
            {
                OnrotationChanging(value);
                ReportPropertyChanging("rotation");
                _rotation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rotation");
                OnrotationChanged();
            }
        }
        private Nullable<global::System.Int32> _rotation;
        partial void OnrotationChanging(Nullable<global::System.Int32> value);
        partial void OnrotationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_lgameModel", "themes_english_pictures_tid_fk", "themes")]
        public theme theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<theme>("db_lgameModel.themes_english_pictures_tid_fk", "themes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<theme>("db_lgameModel.themes_english_pictures_tid_fk", "themes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<theme> themeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<theme>("db_lgameModel.themes_english_pictures_tid_fk", "themes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<theme>("db_lgameModel.themes_english_pictures_tid_fk", "themes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_lgameModel", Name="word")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class word : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new word object.
        /// </summary>
        /// <param name="fakeid">Initial value of the fakeid property.</param>
        public static word Createword(global::System.Int32 fakeid)
        {
            word word = new word();
            word.fakeid = fakeid;
            return word;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private Nullable<global::System.Int32> _id;
        partial void OnidChanging(Nullable<global::System.Int32> value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tid
        {
            get
            {
                return _tid;
            }
            set
            {
                OntidChanging(value);
                ReportPropertyChanging("tid");
                _tid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tid");
                OntidChanged();
            }
        }
        private Nullable<global::System.Int32> _tid;
        partial void OntidChanging(Nullable<global::System.Int32> value);
        partial void OntidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pic_url
        {
            get
            {
                return _pic_url;
            }
            set
            {
                Onpic_urlChanging(value);
                ReportPropertyChanging("pic_url");
                _pic_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pic_url");
                Onpic_urlChanged();
            }
        }
        private global::System.String _pic_url;
        partial void Onpic_urlChanging(global::System.String value);
        partial void Onpic_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String back_clr
        {
            get
            {
                return _back_clr;
            }
            set
            {
                Onback_clrChanging(value);
                ReportPropertyChanging("back_clr");
                _back_clr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("back_clr");
                Onback_clrChanged();
            }
        }
        private global::System.String _back_clr;
        partial void Onback_clrChanging(global::System.String value);
        partial void Onback_clrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String border_clr
        {
            get
            {
                return _border_clr;
            }
            set
            {
                Onborder_clrChanging(value);
                ReportPropertyChanging("border_clr");
                _border_clr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("border_clr");
                Onborder_clrChanged();
            }
        }
        private global::System.String _border_clr;
        partial void Onborder_clrChanging(global::System.String value);
        partial void Onborder_clrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String left_clr
        {
            get
            {
                return _left_clr;
            }
            set
            {
                Onleft_clrChanging(value);
                ReportPropertyChanging("left_clr");
                _left_clr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("left_clr");
                Onleft_clrChanged();
            }
        }
        private global::System.String _left_clr;
        partial void Onleft_clrChanging(global::System.String value);
        partial void Onleft_clrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String top_clr
        {
            get
            {
                return _top_clr;
            }
            set
            {
                Ontop_clrChanging(value);
                ReportPropertyChanging("top_clr");
                _top_clr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("top_clr");
                Ontop_clrChanged();
            }
        }
        private global::System.String _top_clr;
        partial void Ontop_clrChanging(global::System.String value);
        partial void Ontop_clrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String left_top_clr
        {
            get
            {
                return _left_top_clr;
            }
            set
            {
                Onleft_top_clrChanging(value);
                ReportPropertyChanging("left_top_clr");
                _left_top_clr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("left_top_clr");
                Onleft_top_clrChanged();
            }
        }
        private global::System.String _left_top_clr;
        partial void Onleft_top_clrChanging(global::System.String value);
        partial void Onleft_top_clrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fakeid
        {
            get
            {
                return _fakeid;
            }
            set
            {
                if (_fakeid != value)
                {
                    OnfakeidChanging(value);
                    ReportPropertyChanging("fakeid");
                    _fakeid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fakeid");
                    OnfakeidChanged();
                }
            }
        }
        private global::System.Int32 _fakeid;
        partial void OnfakeidChanging(global::System.Int32 value);
        partial void OnfakeidChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_lgameModel", "words_tid_fk", "themes")]
        public theme theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<theme>("db_lgameModel.words_tid_fk", "themes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<theme>("db_lgameModel.words_tid_fk", "themes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<theme> themeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<theme>("db_lgameModel.words_tid_fk", "themes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<theme>("db_lgameModel.words_tid_fk", "themes", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_lgameModel", Name="words_english")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class words_english : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new words_english object.
        /// </summary>
        /// <param name="wid">Initial value of the wid property.</param>
        /// <param name="fakeid">Initial value of the fakeid property.</param>
        public static words_english Createwords_english(global::System.Int32 wid, global::System.Int32 fakeid)
        {
            words_english words_english = new words_english();
            words_english.wid = wid;
            words_english.fakeid = fakeid;
            return words_english;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 wid
        {
            get
            {
                return _wid;
            }
            set
            {
                OnwidChanging(value);
                ReportPropertyChanging("wid");
                _wid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("wid");
                OnwidChanged();
            }
        }
        private global::System.Int32 _wid;
        partial void OnwidChanging(global::System.Int32 value);
        partial void OnwidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String audio_url
        {
            get
            {
                return _audio_url;
            }
            set
            {
                Onaudio_urlChanging(value);
                ReportPropertyChanging("audio_url");
                _audio_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("audio_url");
                Onaudio_urlChanged();
            }
        }
        private global::System.String _audio_url;
        partial void Onaudio_urlChanging(global::System.String value);
        partial void Onaudio_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 fakeid
        {
            get
            {
                return _fakeid;
            }
            set
            {
                if (_fakeid != value)
                {
                    OnfakeidChanging(value);
                    ReportPropertyChanging("fakeid");
                    _fakeid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("fakeid");
                    OnfakeidChanged();
                }
            }
        }
        private global::System.Int32 _fakeid;
        partial void OnfakeidChanging(global::System.Int32 value);
        partial void OnfakeidChanged();

        #endregion

    
    }

    #endregion

    
}
