//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGservices.ThemesUpdaterProxy {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://tempuri.org/")]
    public partial class Language : object, System.ComponentModel.INotifyPropertyChanged {
        
        private uint IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public uint ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Theme", Namespace="http://tempuri.org/")]
    public partial class Theme : LGservices.ThemesUpdaterProxy.Item {
        
        private LGservices.ThemesUpdaterProxy.Symbol[] NameInLettersField;
        
        private LGservices.ThemesUpdaterProxy.Word[] WordsField;
        
        private uint IDField;
        
        private string NameField;
        
        private LGservices.ThemesUpdaterProxy.Level HLevelField;
        
        private string PathDataField;
        
        private LGservices.ThemesUpdaterProxy.License LicenseInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public LGservices.ThemesUpdaterProxy.Symbol[] NameInLetters {
            get {
                return this.NameInLettersField;
            }
            set {
                if ((object.ReferenceEquals(this.NameInLettersField, value) != true)) {
                    this.NameInLettersField = value;
                    this.RaisePropertyChanged("NameInLetters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public LGservices.ThemesUpdaterProxy.Word[] Words {
            get {
                return this.WordsField;
            }
            set {
                if ((object.ReferenceEquals(this.WordsField, value) != true)) {
                    this.WordsField = value;
                    this.RaisePropertyChanged("Words");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public uint ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public LGservices.ThemesUpdaterProxy.Level HLevel {
            get {
                return this.HLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.HLevelField, value) != true)) {
                    this.HLevelField = value;
                    this.RaisePropertyChanged("HLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PathData {
            get {
                return this.PathDataField;
            }
            set {
                if ((object.ReferenceEquals(this.PathDataField, value) != true)) {
                    this.PathDataField = value;
                    this.RaisePropertyChanged("PathData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public LGservices.ThemesUpdaterProxy.License LicenseInfo {
            get {
                return this.LicenseInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseInfoField, value) != true)) {
                    this.LicenseInfoField = value;
                    this.RaisePropertyChanged("LicenseInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LGservices.ThemesUpdaterProxy.Word))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LGservices.ThemesUpdaterProxy.Symbol))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LGservices.ThemesUpdaterProxy.Theme))]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ValueField;
        
        private double WidthField;
        
        private double HeightField;
        
        private double LeftField;
        
        private double TopField;
        
        private double RotationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Left {
            get {
                return this.LeftField;
            }
            set {
                if ((this.LeftField.Equals(value) != true)) {
                    this.LeftField = value;
                    this.RaisePropertyChanged("Left");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Top {
            get {
                return this.TopField;
            }
            set {
                if ((this.TopField.Equals(value) != true)) {
                    this.TopField = value;
                    this.RaisePropertyChanged("Top");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Rotation {
            get {
                return this.RotationField;
            }
            set {
                if ((this.RotationField.Equals(value) != true)) {
                    this.RotationField = value;
                    this.RaisePropertyChanged("Rotation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://tempuri.org/")]
    public partial class Word : LGservices.ThemesUpdaterProxy.Item {
        
        private uint IDField;
        
        private string PictureUrlField;
        
        private string AudioUrlField;
        
        private LGservices.ThemesUpdaterProxy.Color BackColorField;
        
        private LGservices.ThemesUpdaterProxy.Color BorderColorField;
        
        private LGservices.ThemesUpdaterProxy.Color LeftColorField;
        
        private LGservices.ThemesUpdaterProxy.Color TopColorField;
        
        private LGservices.ThemesUpdaterProxy.Color LeftTopColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public uint ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PictureUrl {
            get {
                return this.PictureUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureUrlField, value) != true)) {
                    this.PictureUrlField = value;
                    this.RaisePropertyChanged("PictureUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AudioUrl {
            get {
                return this.AudioUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.AudioUrlField, value) != true)) {
                    this.AudioUrlField = value;
                    this.RaisePropertyChanged("AudioUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public LGservices.ThemesUpdaterProxy.Color BackColor {
            get {
                return this.BackColorField;
            }
            set {
                if ((object.ReferenceEquals(this.BackColorField, value) != true)) {
                    this.BackColorField = value;
                    this.RaisePropertyChanged("BackColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public LGservices.ThemesUpdaterProxy.Color BorderColor {
            get {
                return this.BorderColorField;
            }
            set {
                if ((object.ReferenceEquals(this.BorderColorField, value) != true)) {
                    this.BorderColorField = value;
                    this.RaisePropertyChanged("BorderColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public LGservices.ThemesUpdaterProxy.Color LeftColor {
            get {
                return this.LeftColorField;
            }
            set {
                if ((object.ReferenceEquals(this.LeftColorField, value) != true)) {
                    this.LeftColorField = value;
                    this.RaisePropertyChanged("LeftColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public LGservices.ThemesUpdaterProxy.Color TopColor {
            get {
                return this.TopColorField;
            }
            set {
                if ((object.ReferenceEquals(this.TopColorField, value) != true)) {
                    this.TopColorField = value;
                    this.RaisePropertyChanged("TopColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public LGservices.ThemesUpdaterProxy.Color LeftTopColor {
            get {
                return this.LeftTopColorField;
            }
            set {
                if ((object.ReferenceEquals(this.LeftTopColorField, value) != true)) {
                    this.LeftTopColorField = value;
                    this.RaisePropertyChanged("LeftTopColor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Symbol", Namespace="http://tempuri.org/")]
    public partial class Symbol : LGservices.ThemesUpdaterProxy.Item {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Level", Namespace="http://tempuri.org/")]
    public partial class Level : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int NumberField;
        
        private string NameField;
        
        private string PictureUrlField;
        
        private LGservices.ThemesUpdaterProxy.Color TopColorField;
        
        private LGservices.ThemesUpdaterProxy.Color BottomColorField;
        
        private int BestTimeResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PictureUrl {
            get {
                return this.PictureUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureUrlField, value) != true)) {
                    this.PictureUrlField = value;
                    this.RaisePropertyChanged("PictureUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public LGservices.ThemesUpdaterProxy.Color TopColor {
            get {
                return this.TopColorField;
            }
            set {
                if ((object.ReferenceEquals(this.TopColorField, value) != true)) {
                    this.TopColorField = value;
                    this.RaisePropertyChanged("TopColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public LGservices.ThemesUpdaterProxy.Color BottomColor {
            get {
                return this.BottomColorField;
            }
            set {
                if ((object.ReferenceEquals(this.BottomColorField, value) != true)) {
                    this.BottomColorField = value;
                    this.RaisePropertyChanged("BottomColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int BestTimeResult {
            get {
                return this.BestTimeResultField;
            }
            set {
                if ((this.BestTimeResultField.Equals(value) != true)) {
                    this.BestTimeResultField = value;
                    this.RaisePropertyChanged("BestTimeResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="License", Namespace="http://tempuri.org/")]
    public partial class License : object, System.ComponentModel.INotifyPropertyChanged {
        
        private uint IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public uint ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Color", Namespace="http://tempuri.org/")]
    public partial class Color : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte AField;
        
        private byte BField;
        
        private byte GField;
        
        private byte RField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte A {
            get {
                return this.AField;
            }
            set {
                if ((this.AField.Equals(value) != true)) {
                    this.AField = value;
                    this.RaisePropertyChanged("A");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte B {
            get {
                return this.BField;
            }
            set {
                if ((this.BField.Equals(value) != true)) {
                    this.BField = value;
                    this.RaisePropertyChanged("B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte G {
            get {
                return this.GField;
            }
            set {
                if ((this.GField.Equals(value) != true)) {
                    this.GField = value;
                    this.RaisePropertyChanged("G");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte R {
            get {
                return this.RField;
            }
            set {
                if ((this.RField.Equals(value) != true)) {
                    this.RField = value;
                    this.RaisePropertyChanged("R");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ThemesUpdaterProxy.ThemesUpdaterSoap")]
    public interface ThemesUpdaterSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(LGservices.ThemesUpdaterProxy.HelloWorldRequest request, System.AsyncCallback callback, object asyncState);
        
        LGservices.ThemesUpdaterProxy.HelloWorldResponse EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetNewThemes", ReplyAction="*")]
        System.IAsyncResult BeginGetNewThemes(LGservices.ThemesUpdaterProxy.GetNewThemesRequest request, System.AsyncCallback callback, object asyncState);
        
        LGservices.ThemesUpdaterProxy.GetNewThemesResponse EndGetNewThemes(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(LGservices.ThemesUpdaterProxy.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(LGservices.ThemesUpdaterProxy.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class GetNewThemesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewThemes", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.GetNewThemesRequestBody Body;
        
        public GetNewThemesRequest() {
        }
        
        public GetNewThemesRequest(LGservices.ThemesUpdaterProxy.GetNewThemesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewThemesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LGservices.ThemesUpdaterProxy.Language lang;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int themeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int take;
        
        public GetNewThemesRequestBody() {
        }
        
        public GetNewThemesRequestBody(LGservices.ThemesUpdaterProxy.Language lang, int themeId, int take) {
            this.lang = lang;
            this.themeId = themeId;
            this.take = take;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute()]
    public partial class GetNewThemesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewThemesResponse", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.GetNewThemesResponseBody Body;
        
        public GetNewThemesResponse() {
        }
        
        public GetNewThemesResponse(LGservices.ThemesUpdaterProxy.GetNewThemesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewThemesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LGservices.ThemesUpdaterProxy.Theme[] GetNewThemesResult;
        
        public GetNewThemesResponseBody() {
        }
        
        public GetNewThemesResponseBody(LGservices.ThemesUpdaterProxy.Theme[] GetNewThemesResult) {
            this.GetNewThemesResult = GetNewThemesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ThemesUpdaterSoapChannel : LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNewThemesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNewThemesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public LGservices.ThemesUpdaterProxy.Theme[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((LGservices.ThemesUpdaterProxy.Theme[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ThemesUpdaterSoapClient : System.ServiceModel.ClientBase<LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap>, LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetNewThemesDelegate;
        
        private EndOperationDelegate onEndGetNewThemesDelegate;
        
        private System.Threading.SendOrPostCallback onGetNewThemesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ThemesUpdaterSoapClient() : 
                base(ThemesUpdaterSoapClient.GetDefaultBinding(), ThemesUpdaterSoapClient.GetDefaultEndpointAddress()) {
        }
        
        public ThemesUpdaterSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ThemesUpdaterSoapClient.GetBindingForEndpoint(endpointConfiguration), ThemesUpdaterSoapClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public ThemesUpdaterSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ThemesUpdaterSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public ThemesUpdaterSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ThemesUpdaterSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public ThemesUpdaterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<GetNewThemesCompletedEventArgs> GetNewThemesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.BeginHelloWorld(LGservices.ThemesUpdaterProxy.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            LGservices.ThemesUpdaterProxy.HelloWorldRequest inValue = new LGservices.ThemesUpdaterProxy.HelloWorldRequest();
            inValue.Body = new LGservices.ThemesUpdaterProxy.HelloWorldRequestBody();
            return ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).BeginHelloWorld(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LGservices.ThemesUpdaterProxy.HelloWorldResponse LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndHelloWorld(System.IAsyncResult result) {
            LGservices.ThemesUpdaterProxy.HelloWorldResponse retVal = ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).EndHelloWorld(result);
            return retVal.Body.HelloWorldResult;
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.BeginGetNewThemes(LGservices.ThemesUpdaterProxy.GetNewThemesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNewThemes(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetNewThemes(LGservices.ThemesUpdaterProxy.Language lang, int themeId, int take, System.AsyncCallback callback, object asyncState) {
            LGservices.ThemesUpdaterProxy.GetNewThemesRequest inValue = new LGservices.ThemesUpdaterProxy.GetNewThemesRequest();
            inValue.Body = new LGservices.ThemesUpdaterProxy.GetNewThemesRequestBody();
            inValue.Body.lang = lang;
            inValue.Body.themeId = themeId;
            inValue.Body.take = take;
            return ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).BeginGetNewThemes(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LGservices.ThemesUpdaterProxy.GetNewThemesResponse LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.EndGetNewThemes(System.IAsyncResult result) {
            return base.Channel.EndGetNewThemes(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private LGservices.ThemesUpdaterProxy.Theme[] EndGetNewThemes(System.IAsyncResult result) {
            LGservices.ThemesUpdaterProxy.GetNewThemesResponse retVal = ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).EndGetNewThemes(result);
            return retVal.Body.GetNewThemesResult;
        }
        
        private System.IAsyncResult OnBeginGetNewThemes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            LGservices.ThemesUpdaterProxy.Language lang = ((LGservices.ThemesUpdaterProxy.Language)(inValues[0]));
            int themeId = ((int)(inValues[1]));
            int take = ((int)(inValues[2]));
            return this.BeginGetNewThemes(lang, themeId, take, callback, asyncState);
        }
        
        private object[] OnEndGetNewThemes(System.IAsyncResult result) {
            LGservices.ThemesUpdaterProxy.Theme[] retVal = this.EndGetNewThemes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNewThemesCompleted(object state) {
            if ((this.GetNewThemesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNewThemesCompleted(this, new GetNewThemesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNewThemesAsync(LGservices.ThemesUpdaterProxy.Language lang, int themeId, int take) {
            this.GetNewThemesAsync(lang, themeId, take, null);
        }
        
        public void GetNewThemesAsync(LGservices.ThemesUpdaterProxy.Language lang, int themeId, int take, object userState) {
            if ((this.onBeginGetNewThemesDelegate == null)) {
                this.onBeginGetNewThemesDelegate = new BeginOperationDelegate(this.OnBeginGetNewThemes);
            }
            if ((this.onEndGetNewThemesDelegate == null)) {
                this.onEndGetNewThemesDelegate = new EndOperationDelegate(this.OnEndGetNewThemes);
            }
            if ((this.onGetNewThemesCompletedDelegate == null)) {
                this.onGetNewThemesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNewThemesCompleted);
            }
            base.InvokeAsync(this.onBeginGetNewThemesDelegate, new object[] {
                        lang,
                        themeId,
                        take}, this.onEndGetNewThemesDelegate, this.onGetNewThemesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap CreateChannel() {
            return new ThemesUpdaterSoapClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ThemesUpdaterSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ThemesUpdaterSoap)) {
                return new System.ServiceModel.EndpointAddress("http://localhost/LGserver/ThemesUpdater.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ThemesUpdaterSoapClient.GetBindingForEndpoint(EndpointConfiguration.ThemesUpdaterSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ThemesUpdaterSoapClient.GetEndpointAddress(EndpointConfiguration.ThemesUpdaterSoap);
        }
        
        private class ThemesUpdaterSoapClientChannel : ChannelBase<LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap>, LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap {
            
            public ThemesUpdaterSoapClientChannel(System.ServiceModel.ClientBase<LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHelloWorld(LGservices.ThemesUpdaterProxy.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public LGservices.ThemesUpdaterProxy.HelloWorldResponse EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                LGservices.ThemesUpdaterProxy.HelloWorldResponse _result = ((LGservices.ThemesUpdaterProxy.HelloWorldResponse)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetNewThemes(LGservices.ThemesUpdaterProxy.GetNewThemesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetNewThemes", _args, callback, asyncState);
                return _result;
            }
            
            public LGservices.ThemesUpdaterProxy.GetNewThemesResponse EndGetNewThemes(System.IAsyncResult result) {
                object[] _args = new object[0];
                LGservices.ThemesUpdaterProxy.GetNewThemesResponse _result = ((LGservices.ThemesUpdaterProxy.GetNewThemesResponse)(base.EndInvoke("GetNewThemes", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            ThemesUpdaterSoap,
        }
    }
}
