//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace LGservices.ThemesUpdaterProxy {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="http://tempuri.org/")]
    public partial class Language : object, System.ComponentModel.INotifyPropertyChanged {
        
        private uint IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public uint ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Theme", Namespace="http://tempuri.org/")]
    public partial class Theme : LGservices.ThemesUpdaterProxy.Item {
        
        private System.Collections.Generic.List<LGservices.ThemesUpdaterProxy.Symbol> NameInLettersField;
        
        private System.Collections.Generic.List<LGservices.ThemesUpdaterProxy.Word> WordsField;
        
        private int IDField;
        
        private string NameField;
        
        private string NativeNameField;
        
        private LGservices.ThemesUpdaterProxy.License LicenseInfoField;
        
        private LGservices.ThemesUpdaterProxy.Level HLevelField;
        
        private string PathDataField;
        
        private bool IsPreviewModeField;
        
        private bool IsPreviewsLoadedField;
        
        private bool IsResourcesLoadedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<LGservices.ThemesUpdaterProxy.Symbol> NameInLetters {
            get {
                return this.NameInLettersField;
            }
            set {
                if ((object.ReferenceEquals(this.NameInLettersField, value) != true)) {
                    this.NameInLettersField = value;
                    this.RaisePropertyChanged("NameInLetters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<LGservices.ThemesUpdaterProxy.Word> Words {
            get {
                return this.WordsField;
            }
            set {
                if ((object.ReferenceEquals(this.WordsField, value) != true)) {
                    this.WordsField = value;
                    this.RaisePropertyChanged("Words");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NativeName {
            get {
                return this.NativeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NativeNameField, value) != true)) {
                    this.NativeNameField = value;
                    this.RaisePropertyChanged("NativeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public LGservices.ThemesUpdaterProxy.License LicenseInfo {
            get {
                return this.LicenseInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseInfoField, value) != true)) {
                    this.LicenseInfoField = value;
                    this.RaisePropertyChanged("LicenseInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public LGservices.ThemesUpdaterProxy.Level HLevel {
            get {
                return this.HLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.HLevelField, value) != true)) {
                    this.HLevelField = value;
                    this.RaisePropertyChanged("HLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PathData {
            get {
                return this.PathDataField;
            }
            set {
                if ((object.ReferenceEquals(this.PathDataField, value) != true)) {
                    this.PathDataField = value;
                    this.RaisePropertyChanged("PathData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool IsPreviewMode {
            get {
                return this.IsPreviewModeField;
            }
            set {
                if ((this.IsPreviewModeField.Equals(value) != true)) {
                    this.IsPreviewModeField = value;
                    this.RaisePropertyChanged("IsPreviewMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool IsPreviewsLoaded {
            get {
                return this.IsPreviewsLoadedField;
            }
            set {
                if ((this.IsPreviewsLoadedField.Equals(value) != true)) {
                    this.IsPreviewsLoadedField = value;
                    this.RaisePropertyChanged("IsPreviewsLoaded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool IsResourcesLoaded {
            get {
                return this.IsResourcesLoadedField;
            }
            set {
                if ((this.IsResourcesLoadedField.Equals(value) != true)) {
                    this.IsResourcesLoadedField = value;
                    this.RaisePropertyChanged("IsResourcesLoaded");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LGservices.ThemesUpdaterProxy.Word))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LGservices.ThemesUpdaterProxy.Symbol))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LGservices.ThemesUpdaterProxy.Theme))]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ValueField;
        
        private double WidthField;
        
        private double HeightField;
        
        private double LeftField;
        
        private double TopField;
        
        private double RotationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Left {
            get {
                return this.LeftField;
            }
            set {
                if ((this.LeftField.Equals(value) != true)) {
                    this.LeftField = value;
                    this.RaisePropertyChanged("Left");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Top {
            get {
                return this.TopField;
            }
            set {
                if ((this.TopField.Equals(value) != true)) {
                    this.TopField = value;
                    this.RaisePropertyChanged("Top");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Rotation {
            get {
                return this.RotationField;
            }
            set {
                if ((this.RotationField.Equals(value) != true)) {
                    this.RotationField = value;
                    this.RaisePropertyChanged("Rotation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://tempuri.org/")]
    public partial class Word : LGservices.ThemesUpdaterProxy.Item {
        
        private int IDField;
        
        private string PictureUrlField;
        
        private string AudioUrlField;
        
        private LGservices.ThemesUpdaterProxy.Color BackColorField;
        
        private LGservices.ThemesUpdaterProxy.Color BorderColorField;
        
        private LGservices.ThemesUpdaterProxy.Color LeftColorField;
        
        private LGservices.ThemesUpdaterProxy.Color TopColorField;
        
        private LGservices.ThemesUpdaterProxy.Color LeftTopColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PictureUrl {
            get {
                return this.PictureUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureUrlField, value) != true)) {
                    this.PictureUrlField = value;
                    this.RaisePropertyChanged("PictureUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AudioUrl {
            get {
                return this.AudioUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.AudioUrlField, value) != true)) {
                    this.AudioUrlField = value;
                    this.RaisePropertyChanged("AudioUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public LGservices.ThemesUpdaterProxy.Color BackColor {
            get {
                return this.BackColorField;
            }
            set {
                if ((object.ReferenceEquals(this.BackColorField, value) != true)) {
                    this.BackColorField = value;
                    this.RaisePropertyChanged("BackColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public LGservices.ThemesUpdaterProxy.Color BorderColor {
            get {
                return this.BorderColorField;
            }
            set {
                if ((object.ReferenceEquals(this.BorderColorField, value) != true)) {
                    this.BorderColorField = value;
                    this.RaisePropertyChanged("BorderColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public LGservices.ThemesUpdaterProxy.Color LeftColor {
            get {
                return this.LeftColorField;
            }
            set {
                if ((object.ReferenceEquals(this.LeftColorField, value) != true)) {
                    this.LeftColorField = value;
                    this.RaisePropertyChanged("LeftColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public LGservices.ThemesUpdaterProxy.Color TopColor {
            get {
                return this.TopColorField;
            }
            set {
                if ((object.ReferenceEquals(this.TopColorField, value) != true)) {
                    this.TopColorField = value;
                    this.RaisePropertyChanged("TopColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public LGservices.ThemesUpdaterProxy.Color LeftTopColor {
            get {
                return this.LeftTopColorField;
            }
            set {
                if ((object.ReferenceEquals(this.LeftTopColorField, value) != true)) {
                    this.LeftTopColorField = value;
                    this.RaisePropertyChanged("LeftTopColor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Symbol", Namespace="http://tempuri.org/")]
    public partial class Symbol : LGservices.ThemesUpdaterProxy.Item {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="License", Namespace="http://tempuri.org/")]
    public partial class License : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string IDField;
        
        private bool IsActiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Level", Namespace="http://tempuri.org/")]
    public partial class Level : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int NumberField;
        
        private string NameField;
        
        private string PictureUrlField;
        
        private LGservices.ThemesUpdaterProxy.Color TopColorField;
        
        private LGservices.ThemesUpdaterProxy.Color BottomColorField;
        
        private int BestTimeResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PictureUrl {
            get {
                return this.PictureUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureUrlField, value) != true)) {
                    this.PictureUrlField = value;
                    this.RaisePropertyChanged("PictureUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public LGservices.ThemesUpdaterProxy.Color TopColor {
            get {
                return this.TopColorField;
            }
            set {
                if ((object.ReferenceEquals(this.TopColorField, value) != true)) {
                    this.TopColorField = value;
                    this.RaisePropertyChanged("TopColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public LGservices.ThemesUpdaterProxy.Color BottomColor {
            get {
                return this.BottomColorField;
            }
            set {
                if ((object.ReferenceEquals(this.BottomColorField, value) != true)) {
                    this.BottomColorField = value;
                    this.RaisePropertyChanged("BottomColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int BestTimeResult {
            get {
                return this.BestTimeResultField;
            }
            set {
                if ((this.BestTimeResultField.Equals(value) != true)) {
                    this.BestTimeResultField = value;
                    this.RaisePropertyChanged("BestTimeResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Color", Namespace="http://tempuri.org/")]
    public partial class Color : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte AField;
        
        private byte BField;
        
        private byte GField;
        
        private byte RField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte A {
            get {
                return this.AField;
            }
            set {
                if ((this.AField.Equals(value) != true)) {
                    this.AField = value;
                    this.RaisePropertyChanged("A");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte B {
            get {
                return this.BField;
            }
            set {
                if ((this.BField.Equals(value) != true)) {
                    this.BField = value;
                    this.RaisePropertyChanged("B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte G {
            get {
                return this.GField;
            }
            set {
                if ((this.GField.Equals(value) != true)) {
                    this.GField = value;
                    this.RaisePropertyChanged("G");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte R {
            get {
                return this.RField;
            }
            set {
                if ((this.RField.Equals(value) != true)) {
                    this.RField = value;
                    this.RaisePropertyChanged("R");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileDAL", Namespace="http://tempuri.org/")]
    public partial class ProfileDAL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private string NameField;
        
        private string PasswordField;
        
        private string ContactInfoField;
        
        private string PictureUrlField;
        
        private byte[] PictureField;
        
        private int TypeField;
        
        private int LastThemeIDField;
        
        private int TimePlayedField;
        
        private int BestTimeField;
        
        private bool HasPhotoField;
        
        private System.Collections.Generic.List<LGservices.ThemesUpdaterProxy.Theme> ThemesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ContactInfo {
            get {
                return this.ContactInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactInfoField, value) != true)) {
                    this.ContactInfoField = value;
                    this.RaisePropertyChanged("ContactInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PictureUrl {
            get {
                return this.PictureUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureUrlField, value) != true)) {
                    this.PictureUrlField = value;
                    this.RaisePropertyChanged("PictureUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int LastThemeID {
            get {
                return this.LastThemeIDField;
            }
            set {
                if ((this.LastThemeIDField.Equals(value) != true)) {
                    this.LastThemeIDField = value;
                    this.RaisePropertyChanged("LastThemeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int TimePlayed {
            get {
                return this.TimePlayedField;
            }
            set {
                if ((this.TimePlayedField.Equals(value) != true)) {
                    this.TimePlayedField = value;
                    this.RaisePropertyChanged("TimePlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int BestTime {
            get {
                return this.BestTimeField;
            }
            set {
                if ((this.BestTimeField.Equals(value) != true)) {
                    this.BestTimeField = value;
                    this.RaisePropertyChanged("BestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool HasPhoto {
            get {
                return this.HasPhotoField;
            }
            set {
                if ((this.HasPhotoField.Equals(value) != true)) {
                    this.HasPhotoField = value;
                    this.RaisePropertyChanged("HasPhoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public System.Collections.Generic.List<LGservices.ThemesUpdaterProxy.Theme> Themes {
            get {
                return this.ThemesField;
            }
            set {
                if ((object.ReferenceEquals(this.ThemesField, value) != true)) {
                    this.ThemesField = value;
                    this.RaisePropertyChanged("Themes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LevelProfiles", Namespace="http://tempuri.org/")]
    public partial class LevelProfiles : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<LGservices.ThemesUpdaterProxy.ProfileDAL> ProfilesField;
        
        private int TotalLevelPlayersField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<LGservices.ThemesUpdaterProxy.ProfileDAL> Profiles {
            get {
                return this.ProfilesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfilesField, value) != true)) {
                    this.ProfilesField = value;
                    this.RaisePropertyChanged("Profiles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalLevelPlayers {
            get {
                return this.TotalLevelPlayersField;
            }
            set {
                if ((this.TotalLevelPlayersField.Equals(value) != true)) {
                    this.TotalLevelPlayersField = value;
                    this.RaisePropertyChanged("TotalLevelPlayers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ThemesUpdaterProxy.ThemesUpdaterSoap")]
    public interface ThemesUpdaterSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWebThemeUpdaterUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetWebThemeUpdaterUrlResponse> GetWebThemeUpdaterUrlAsync(LGservices.ThemesUpdaterProxy.GetWebThemeUpdaterUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogErrorToServe", ReplyAction="*")]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.LogErrorToServeResponse> LogErrorToServeAsync(LGservices.ThemesUpdaterProxy.LogErrorToServeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileStorageBaseUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetFileStorageBaseUrlResponse> GetFileStorageBaseUrlAsync(LGservices.ThemesUpdaterProxy.GetFileStorageBaseUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNewThemes", ReplyAction="*")]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetNewThemesResponse> GetNewThemesAsync(LGservices.ThemesUpdaterProxy.GetNewThemesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFullThemesData", ReplyAction="*")]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetFullThemesDataResponse> GetFullThemesDataAsync(LGservices.ThemesUpdaterProxy.GetFullThemesDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.AddProfileResponse> AddProfileAsync(LGservices.ThemesUpdaterProxy.AddProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.UpdateProfileResponse> UpdateProfileAsync(LGservices.ThemesUpdaterProxy.UpdateProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.DeleteProfileResponse> DeleteProfileAsync(LGservices.ThemesUpdaterProxy.DeleteProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckIfBecomesOrRemainsAllSeeing", ReplyAction="*")]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.CheckIfBecomesOrRemainsAllSeeingResponse> CheckIfBecomesOrRemainsAllSeeingAsync(LGservices.ThemesUpdaterProxy.CheckIfBecomesOrRemainsAllSeeingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProfileLevel", ReplyAction="*")]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.UpdateProfileLevelResponse> UpdateProfileLevelAsync(LGservices.ThemesUpdaterProxy.UpdateProfileLevelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProfiles", ReplyAction="*")]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetProfilesResponse> GetProfilesAsync(LGservices.ThemesUpdaterProxy.GetProfilesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebThemeUpdaterUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebThemeUpdaterUrl", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.GetWebThemeUpdaterUrlRequestBody Body;
        
        public GetWebThemeUpdaterUrlRequest() {
        }
        
        public GetWebThemeUpdaterUrlRequest(LGservices.ThemesUpdaterProxy.GetWebThemeUpdaterUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWebThemeUpdaterUrlRequestBody {
        
        public GetWebThemeUpdaterUrlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebThemeUpdaterUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebThemeUpdaterUrlResponse", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.GetWebThemeUpdaterUrlResponseBody Body;
        
        public GetWebThemeUpdaterUrlResponse() {
        }
        
        public GetWebThemeUpdaterUrlResponse(LGservices.ThemesUpdaterProxy.GetWebThemeUpdaterUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWebThemeUpdaterUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWebThemeUpdaterUrlResult;
        
        public GetWebThemeUpdaterUrlResponseBody() {
        }
        
        public GetWebThemeUpdaterUrlResponseBody(string GetWebThemeUpdaterUrlResult) {
            this.GetWebThemeUpdaterUrlResult = GetWebThemeUpdaterUrlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogErrorToServeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogErrorToServe", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.LogErrorToServeRequestBody Body;
        
        public LogErrorToServeRequest() {
        }
        
        public LogErrorToServeRequest(LGservices.ThemesUpdaterProxy.LogErrorToServeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogErrorToServeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        public LogErrorToServeRequestBody() {
        }
        
        public LogErrorToServeRequestBody(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogErrorToServeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogErrorToServeResponse", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.LogErrorToServeResponseBody Body;
        
        public LogErrorToServeResponse() {
        }
        
        public LogErrorToServeResponse(LGservices.ThemesUpdaterProxy.LogErrorToServeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogErrorToServeResponseBody {
        
        public LogErrorToServeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileStorageBaseUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileStorageBaseUrl", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.GetFileStorageBaseUrlRequestBody Body;
        
        public GetFileStorageBaseUrlRequest() {
        }
        
        public GetFileStorageBaseUrlRequest(LGservices.ThemesUpdaterProxy.GetFileStorageBaseUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetFileStorageBaseUrlRequestBody {
        
        public GetFileStorageBaseUrlRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileStorageBaseUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileStorageBaseUrlResponse", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.GetFileStorageBaseUrlResponseBody Body;
        
        public GetFileStorageBaseUrlResponse() {
        }
        
        public GetFileStorageBaseUrlResponse(LGservices.ThemesUpdaterProxy.GetFileStorageBaseUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileStorageBaseUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetFileStorageBaseUrlResult;
        
        public GetFileStorageBaseUrlResponseBody() {
        }
        
        public GetFileStorageBaseUrlResponseBody(string GetFileStorageBaseUrlResult) {
            this.GetFileStorageBaseUrlResult = GetFileStorageBaseUrlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewThemesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewThemes", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.GetNewThemesRequestBody Body;
        
        public GetNewThemesRequest() {
        }
        
        public GetNewThemesRequest(LGservices.ThemesUpdaterProxy.GetNewThemesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewThemesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LGservices.ThemesUpdaterProxy.Language lang;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int themeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int take;
        
        public GetNewThemesRequestBody() {
        }
        
        public GetNewThemesRequestBody(LGservices.ThemesUpdaterProxy.Language lang, int themeId, int take) {
            this.lang = lang;
            this.themeId = themeId;
            this.take = take;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewThemesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewThemesResponse", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.GetNewThemesResponseBody Body;
        
        public GetNewThemesResponse() {
        }
        
        public GetNewThemesResponse(LGservices.ThemesUpdaterProxy.GetNewThemesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNewThemesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<LGservices.ThemesUpdaterProxy.Theme> GetNewThemesResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errMessage;
        
        public GetNewThemesResponseBody() {
        }
        
        public GetNewThemesResponseBody(System.Collections.Generic.List<LGservices.ThemesUpdaterProxy.Theme> GetNewThemesResult, string errMessage) {
            this.GetNewThemesResult = GetNewThemesResult;
            this.errMessage = errMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFullThemesDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFullThemesData", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.GetFullThemesDataRequestBody Body;
        
        public GetFullThemesDataRequest() {
        }
        
        public GetFullThemesDataRequest(LGservices.ThemesUpdaterProxy.GetFullThemesDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFullThemesDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LGservices.ThemesUpdaterProxy.Language lang;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public LGservices.ThemesUpdaterProxy.ArrayOfInt ids;
        
        public GetFullThemesDataRequestBody() {
        }
        
        public GetFullThemesDataRequestBody(LGservices.ThemesUpdaterProxy.Language lang, LGservices.ThemesUpdaterProxy.ArrayOfInt ids) {
            this.lang = lang;
            this.ids = ids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFullThemesDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFullThemesDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.GetFullThemesDataResponseBody Body;
        
        public GetFullThemesDataResponse() {
        }
        
        public GetFullThemesDataResponse(LGservices.ThemesUpdaterProxy.GetFullThemesDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFullThemesDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<LGservices.ThemesUpdaterProxy.Theme> GetFullThemesDataResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errMessage;
        
        public GetFullThemesDataResponseBody() {
        }
        
        public GetFullThemesDataResponseBody(System.Collections.Generic.List<LGservices.ThemesUpdaterProxy.Theme> GetFullThemesDataResult, string errMessage) {
            this.GetFullThemesDataResult = GetFullThemesDataResult;
            this.errMessage = errMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProfile", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.AddProfileRequestBody Body;
        
        public AddProfileRequest() {
        }
        
        public AddProfileRequest(LGservices.ThemesUpdaterProxy.AddProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LGservices.ThemesUpdaterProxy.ProfileDAL pdal;
        
        public AddProfileRequestBody() {
        }
        
        public AddProfileRequestBody(LGservices.ThemesUpdaterProxy.ProfileDAL pdal) {
            this.pdal = pdal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.AddProfileResponseBody Body;
        
        public AddProfileResponse() {
        }
        
        public AddProfileResponse(LGservices.ThemesUpdaterProxy.AddProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddProfileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errMessage;
        
        public AddProfileResponseBody() {
        }
        
        public AddProfileResponseBody(int AddProfileResult, string errMessage) {
            this.AddProfileResult = AddProfileResult;
            this.errMessage = errMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProfile", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.UpdateProfileRequestBody Body;
        
        public UpdateProfileRequest() {
        }
        
        public UpdateProfileRequest(LGservices.ThemesUpdaterProxy.UpdateProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LGservices.ThemesUpdaterProxy.ProfileDAL pdal;
        
        public UpdateProfileRequestBody() {
        }
        
        public UpdateProfileRequestBody(LGservices.ThemesUpdaterProxy.ProfileDAL pdal) {
            this.pdal = pdal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.UpdateProfileResponseBody Body;
        
        public UpdateProfileResponse() {
        }
        
        public UpdateProfileResponse(LGservices.ThemesUpdaterProxy.UpdateProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string errMessage;
        
        public UpdateProfileResponseBody() {
        }
        
        public UpdateProfileResponseBody(string errMessage) {
            this.errMessage = errMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProfile", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.DeleteProfileRequestBody Body;
        
        public DeleteProfileRequest() {
        }
        
        public DeleteProfileRequest(LGservices.ThemesUpdaterProxy.DeleteProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public LGservices.ThemesUpdaterProxy.Language lang;
        
        public DeleteProfileRequestBody() {
        }
        
        public DeleteProfileRequestBody(int pid, LGservices.ThemesUpdaterProxy.Language lang) {
            this.pid = pid;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProfileResponse", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.DeleteProfileResponseBody Body;
        
        public DeleteProfileResponse() {
        }
        
        public DeleteProfileResponse(LGservices.ThemesUpdaterProxy.DeleteProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string errMessage;
        
        public DeleteProfileResponseBody() {
        }
        
        public DeleteProfileResponseBody(string errMessage) {
            this.errMessage = errMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckIfBecomesOrRemainsAllSeeingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckIfBecomesOrRemainsAllSeeing", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.CheckIfBecomesOrRemainsAllSeeingRequestBody Body;
        
        public CheckIfBecomesOrRemainsAllSeeingRequest() {
        }
        
        public CheckIfBecomesOrRemainsAllSeeingRequest(LGservices.ThemesUpdaterProxy.CheckIfBecomesOrRemainsAllSeeingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckIfBecomesOrRemainsAllSeeingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LGservices.ThemesUpdaterProxy.Language lang;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int profId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string thName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int bTime;
        
        public CheckIfBecomesOrRemainsAllSeeingRequestBody() {
        }
        
        public CheckIfBecomesOrRemainsAllSeeingRequestBody(LGservices.ThemesUpdaterProxy.Language lang, int profId, string thName, int bTime) {
            this.lang = lang;
            this.profId = profId;
            this.thName = thName;
            this.bTime = bTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckIfBecomesOrRemainsAllSeeingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckIfBecomesOrRemainsAllSeeingResponse", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.CheckIfBecomesOrRemainsAllSeeingResponseBody Body;
        
        public CheckIfBecomesOrRemainsAllSeeingResponse() {
        }
        
        public CheckIfBecomesOrRemainsAllSeeingResponse(LGservices.ThemesUpdaterProxy.CheckIfBecomesOrRemainsAllSeeingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckIfBecomesOrRemainsAllSeeingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckIfBecomesOrRemainsAllSeeingResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errMessage;
        
        public CheckIfBecomesOrRemainsAllSeeingResponseBody() {
        }
        
        public CheckIfBecomesOrRemainsAllSeeingResponseBody(bool CheckIfBecomesOrRemainsAllSeeingResult, string errMessage) {
            this.CheckIfBecomesOrRemainsAllSeeingResult = CheckIfBecomesOrRemainsAllSeeingResult;
            this.errMessage = errMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProfileLevelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProfileLevel", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.UpdateProfileLevelRequestBody Body;
        
        public UpdateProfileLevelRequest() {
        }
        
        public UpdateProfileLevelRequest(LGservices.ThemesUpdaterProxy.UpdateProfileLevelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProfileLevelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LGservices.ThemesUpdaterProxy.ProfileDAL prof;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public LGservices.ThemesUpdaterProxy.Theme th;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public LGservices.ThemesUpdaterProxy.Language lang;
        
        public UpdateProfileLevelRequestBody() {
        }
        
        public UpdateProfileLevelRequestBody(LGservices.ThemesUpdaterProxy.ProfileDAL prof, LGservices.ThemesUpdaterProxy.Theme th, LGservices.ThemesUpdaterProxy.Language lang) {
            this.prof = prof;
            this.th = th;
            this.lang = lang;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProfileLevelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProfileLevelResponse", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.UpdateProfileLevelResponseBody Body;
        
        public UpdateProfileLevelResponse() {
        }
        
        public UpdateProfileLevelResponse(LGservices.ThemesUpdaterProxy.UpdateProfileLevelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProfileLevelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateProfileLevelResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errMessage;
        
        public UpdateProfileLevelResponseBody() {
        }
        
        public UpdateProfileLevelResponseBody(bool UpdateProfileLevelResult, string errMessage) {
            this.UpdateProfileLevelResult = UpdateProfileLevelResult;
            this.errMessage = errMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfiles", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.GetProfilesRequestBody Body;
        
        public GetProfilesRequest() {
        }
        
        public GetProfilesRequest(LGservices.ThemesUpdaterProxy.GetProfilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProfilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LGservices.ThemesUpdaterProxy.Language lang;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string thName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int levNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int skip;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int take;
        
        public GetProfilesRequestBody() {
        }
        
        public GetProfilesRequestBody(LGservices.ThemesUpdaterProxy.Language lang, string thName, int levNo, int skip, int take) {
            this.lang = lang;
            this.thName = thName;
            this.levNo = levNo;
            this.skip = skip;
            this.take = take;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public LGservices.ThemesUpdaterProxy.GetProfilesResponseBody Body;
        
        public GetProfilesResponse() {
        }
        
        public GetProfilesResponse(LGservices.ThemesUpdaterProxy.GetProfilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProfilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LGservices.ThemesUpdaterProxy.LevelProfiles GetProfilesResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errMessage;
        
        public GetProfilesResponseBody() {
        }
        
        public GetProfilesResponseBody(LGservices.ThemesUpdaterProxy.LevelProfiles GetProfilesResult, string errMessage) {
            this.GetProfilesResult = GetProfilesResult;
            this.errMessage = errMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ThemesUpdaterSoapChannel : LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ThemesUpdaterSoapClient : System.ServiceModel.ClientBase<LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap>, LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ThemesUpdaterSoapClient() : 
                base(ThemesUpdaterSoapClient.GetDefaultBinding(), ThemesUpdaterSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.ThemesUpdaterSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThemesUpdaterSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ThemesUpdaterSoapClient.GetBindingForEndpoint(endpointConfiguration), ThemesUpdaterSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThemesUpdaterSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ThemesUpdaterSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThemesUpdaterSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ThemesUpdaterSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ThemesUpdaterSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetWebThemeUpdaterUrlResponse> LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.GetWebThemeUpdaterUrlAsync(LGservices.ThemesUpdaterProxy.GetWebThemeUpdaterUrlRequest request) {
            return base.Channel.GetWebThemeUpdaterUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetWebThemeUpdaterUrlResponse> GetWebThemeUpdaterUrlAsync() {
            LGservices.ThemesUpdaterProxy.GetWebThemeUpdaterUrlRequest inValue = new LGservices.ThemesUpdaterProxy.GetWebThemeUpdaterUrlRequest();
            inValue.Body = new LGservices.ThemesUpdaterProxy.GetWebThemeUpdaterUrlRequestBody();
            return ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).GetWebThemeUpdaterUrlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.LogErrorToServeResponse> LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.LogErrorToServeAsync(LGservices.ThemesUpdaterProxy.LogErrorToServeRequest request) {
            return base.Channel.LogErrorToServeAsync(request);
        }
        
        public System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.LogErrorToServeResponse> LogErrorToServeAsync(string s) {
            LGservices.ThemesUpdaterProxy.LogErrorToServeRequest inValue = new LGservices.ThemesUpdaterProxy.LogErrorToServeRequest();
            inValue.Body = new LGservices.ThemesUpdaterProxy.LogErrorToServeRequestBody();
            inValue.Body.s = s;
            return ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).LogErrorToServeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetFileStorageBaseUrlResponse> LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.GetFileStorageBaseUrlAsync(LGservices.ThemesUpdaterProxy.GetFileStorageBaseUrlRequest request) {
            return base.Channel.GetFileStorageBaseUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetFileStorageBaseUrlResponse> GetFileStorageBaseUrlAsync() {
            LGservices.ThemesUpdaterProxy.GetFileStorageBaseUrlRequest inValue = new LGservices.ThemesUpdaterProxy.GetFileStorageBaseUrlRequest();
            inValue.Body = new LGservices.ThemesUpdaterProxy.GetFileStorageBaseUrlRequestBody();
            return ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).GetFileStorageBaseUrlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetNewThemesResponse> LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.GetNewThemesAsync(LGservices.ThemesUpdaterProxy.GetNewThemesRequest request) {
            return base.Channel.GetNewThemesAsync(request);
        }
        
        public System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetNewThemesResponse> GetNewThemesAsync(LGservices.ThemesUpdaterProxy.Language lang, int themeId, int take) {
            LGservices.ThemesUpdaterProxy.GetNewThemesRequest inValue = new LGservices.ThemesUpdaterProxy.GetNewThemesRequest();
            inValue.Body = new LGservices.ThemesUpdaterProxy.GetNewThemesRequestBody();
            inValue.Body.lang = lang;
            inValue.Body.themeId = themeId;
            inValue.Body.take = take;
            return ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).GetNewThemesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetFullThemesDataResponse> LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.GetFullThemesDataAsync(LGservices.ThemesUpdaterProxy.GetFullThemesDataRequest request) {
            return base.Channel.GetFullThemesDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetFullThemesDataResponse> GetFullThemesDataAsync(LGservices.ThemesUpdaterProxy.Language lang, LGservices.ThemesUpdaterProxy.ArrayOfInt ids) {
            LGservices.ThemesUpdaterProxy.GetFullThemesDataRequest inValue = new LGservices.ThemesUpdaterProxy.GetFullThemesDataRequest();
            inValue.Body = new LGservices.ThemesUpdaterProxy.GetFullThemesDataRequestBody();
            inValue.Body.lang = lang;
            inValue.Body.ids = ids;
            return ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).GetFullThemesDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.AddProfileResponse> LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.AddProfileAsync(LGservices.ThemesUpdaterProxy.AddProfileRequest request) {
            return base.Channel.AddProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.AddProfileResponse> AddProfileAsync(LGservices.ThemesUpdaterProxy.ProfileDAL pdal) {
            LGservices.ThemesUpdaterProxy.AddProfileRequest inValue = new LGservices.ThemesUpdaterProxy.AddProfileRequest();
            inValue.Body = new LGservices.ThemesUpdaterProxy.AddProfileRequestBody();
            inValue.Body.pdal = pdal;
            return ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).AddProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.UpdateProfileResponse> LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.UpdateProfileAsync(LGservices.ThemesUpdaterProxy.UpdateProfileRequest request) {
            return base.Channel.UpdateProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.UpdateProfileResponse> UpdateProfileAsync(LGservices.ThemesUpdaterProxy.ProfileDAL pdal) {
            LGservices.ThemesUpdaterProxy.UpdateProfileRequest inValue = new LGservices.ThemesUpdaterProxy.UpdateProfileRequest();
            inValue.Body = new LGservices.ThemesUpdaterProxy.UpdateProfileRequestBody();
            inValue.Body.pdal = pdal;
            return ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).UpdateProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.DeleteProfileResponse> LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.DeleteProfileAsync(LGservices.ThemesUpdaterProxy.DeleteProfileRequest request) {
            return base.Channel.DeleteProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.DeleteProfileResponse> DeleteProfileAsync(int pid, LGservices.ThemesUpdaterProxy.Language lang) {
            LGservices.ThemesUpdaterProxy.DeleteProfileRequest inValue = new LGservices.ThemesUpdaterProxy.DeleteProfileRequest();
            inValue.Body = new LGservices.ThemesUpdaterProxy.DeleteProfileRequestBody();
            inValue.Body.pid = pid;
            inValue.Body.lang = lang;
            return ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).DeleteProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.CheckIfBecomesOrRemainsAllSeeingResponse> LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.CheckIfBecomesOrRemainsAllSeeingAsync(LGservices.ThemesUpdaterProxy.CheckIfBecomesOrRemainsAllSeeingRequest request) {
            return base.Channel.CheckIfBecomesOrRemainsAllSeeingAsync(request);
        }
        
        public System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.CheckIfBecomesOrRemainsAllSeeingResponse> CheckIfBecomesOrRemainsAllSeeingAsync(LGservices.ThemesUpdaterProxy.Language lang, int profId, string thName, int bTime) {
            LGservices.ThemesUpdaterProxy.CheckIfBecomesOrRemainsAllSeeingRequest inValue = new LGservices.ThemesUpdaterProxy.CheckIfBecomesOrRemainsAllSeeingRequest();
            inValue.Body = new LGservices.ThemesUpdaterProxy.CheckIfBecomesOrRemainsAllSeeingRequestBody();
            inValue.Body.lang = lang;
            inValue.Body.profId = profId;
            inValue.Body.thName = thName;
            inValue.Body.bTime = bTime;
            return ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).CheckIfBecomesOrRemainsAllSeeingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.UpdateProfileLevelResponse> LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.UpdateProfileLevelAsync(LGservices.ThemesUpdaterProxy.UpdateProfileLevelRequest request) {
            return base.Channel.UpdateProfileLevelAsync(request);
        }
        
        public System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.UpdateProfileLevelResponse> UpdateProfileLevelAsync(LGservices.ThemesUpdaterProxy.ProfileDAL prof, LGservices.ThemesUpdaterProxy.Theme th, LGservices.ThemesUpdaterProxy.Language lang) {
            LGservices.ThemesUpdaterProxy.UpdateProfileLevelRequest inValue = new LGservices.ThemesUpdaterProxy.UpdateProfileLevelRequest();
            inValue.Body = new LGservices.ThemesUpdaterProxy.UpdateProfileLevelRequestBody();
            inValue.Body.prof = prof;
            inValue.Body.th = th;
            inValue.Body.lang = lang;
            return ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).UpdateProfileLevelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetProfilesResponse> LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap.GetProfilesAsync(LGservices.ThemesUpdaterProxy.GetProfilesRequest request) {
            return base.Channel.GetProfilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<LGservices.ThemesUpdaterProxy.GetProfilesResponse> GetProfilesAsync(LGservices.ThemesUpdaterProxy.Language lang, string thName, int levNo, int skip, int take) {
            LGservices.ThemesUpdaterProxy.GetProfilesRequest inValue = new LGservices.ThemesUpdaterProxy.GetProfilesRequest();
            inValue.Body = new LGservices.ThemesUpdaterProxy.GetProfilesRequestBody();
            inValue.Body.lang = lang;
            inValue.Body.thName = thName;
            inValue.Body.levNo = levNo;
            inValue.Body.skip = skip;
            inValue.Body.take = take;
            return ((LGservices.ThemesUpdaterProxy.ThemesUpdaterSoap)(this)).GetProfilesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ThemesUpdaterSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.ThemesUpdaterSoap)) {
                return new System.ServiceModel.EndpointAddress("http://localhost/LGserver/ThemesUpdater.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ThemesUpdaterSoapClient.GetBindingForEndpoint(EndpointConfiguration.ThemesUpdaterSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ThemesUpdaterSoapClient.GetEndpointAddress(EndpointConfiguration.ThemesUpdaterSoap);
        }
        
        public enum EndpointConfiguration {
            
            ThemesUpdaterSoap,
        }
    }
}
